name: davdebrid-brent
services:

  davdebrid-brent:
    image: brentwashere/davdebrid-updateminor:always
    container_name: davdebrid-brent
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DEBRID_API_KEY: # Get it on https://debrid-link.com/webapp/apikey
      DATA_FOLDER: /data
      PLEX_URL: http://plex:32400
      PLEX_TOKEN: #enter your token

    networks:
      - default 
    ports:
      - 8080:8080
    volumes:
      - $DOCKERDIR/appdata/davdebrid/data:/data
